@echo off

RMDIR "Extras\Nuget\lib\" /S /Q
RMDIR "Extras\Nuget_Collections\lib\" /S /Q
RMDIR "Extras\Nuget_Utilities\lib\" /S /Q

XCOPY "Optional\bin\Release-Net35\Optional.dll" "Extras\Nuget\lib\net35\" /Y
XCOPY "Optional\bin\Release-Net35\Optional.xml" "Extras\Nuget\lib\net35\" /Y
XCOPY "Optional\bin\Release-Net40\Optional.dll" "Extras\Nuget\lib\net40\" /Y
XCOPY "Optional\bin\Release-Net40\Optional.xml" "Extras\Nuget\lib\net40\" /Y
XCOPY "Optional\bin\Release-Net45\Optional.dll" "Extras\Nuget\lib\net45\" /Y
XCOPY "Optional\bin\Release-Net45\Optional.xml" "Extras\Nuget\lib\net45\" /Y
XCOPY "Optional\bin\Release-Net451\Optional.dll" "Extras\Nuget\lib\net451\" /Y
XCOPY "Optional\bin\Release-Net451\Optional.xml" "Extras\Nuget\lib\net451\" /Y
XCOPY "Optional\bin\Release-Net452\Optional.dll" "Extras\Nuget\lib\net452\" /Y
XCOPY "Optional\bin\Release-Net452\Optional.xml" "Extras\Nuget\lib\net452\" /Y
XCOPY "Optional\bin\Release-Net46\Optional.dll" "Extras\Nuget\lib\net46\" /Y
XCOPY "Optional\bin\Release-Net46\Optional.xml" "Extras\Nuget\lib\net46\" /Y
XCOPY "Optional\bin\Release-Net461\Optional.dll" "Extras\Nuget\lib\net461\" /Y
XCOPY "Optional\bin\Release-Net461\Optional.xml" "Extras\Nuget\lib\net461\" /Y
XCOPY "Optional\bin\Release-Net462\Optional.dll" "Extras\Nuget\lib\net462\" /Y
XCOPY "Optional\bin\Release-Net462\Optional.xml" "Extras\Nuget\lib\net462\" /Y
XCOPY "Portable.Optional\bin\Release\Optional.dll" "Extras\Nuget\lib\netstandard1.0\" /Y
XCOPY "Portable.Optional\bin\Release\Optional.xml" "Extras\Nuget\lib\netstandard1.0\" /Y

XCOPY "Optional.Collections\bin\Release-Net35\Optional.dll" "Extras\Nuget_Collections\lib\net35\" /Y
XCOPY "Optional.Collections\bin\Release-Net35\Optional.xml" "Extras\Nuget_Collections\lib\net35\" /Y
XCOPY "Optional.Collections\bin\Release-Net40\Optional.dll" "Extras\Nuget_Collections\lib\net40\" /Y
XCOPY "Optional.Collections\bin\Release-Net40\Optional.xml" "Extras\Nuget_Collections\lib\net40\" /Y
XCOPY "Optional.Collections\bin\Release-Net45\Optional.dll" "Extras\Nuget_Collections\lib\net45\" /Y
XCOPY "Optional.Collections\bin\Release-Net45\Optional.xml" "Extras\Nuget_Collections\lib\net45\" /Y
XCOPY "Optional.Collections\bin\Release-Net451\Optional.dll" "Extras\Nuget_Collections\lib\net451\" /Y
XCOPY "Optional.Collections\bin\Release-Net451\Optional.xml" "Extras\Nuget_Collections\lib\net451\" /Y
XCOPY "Optional.Collections\bin\Release-Net452\Optional.dll" "Extras\Nuget_Collections\lib\net452\" /Y
XCOPY "Optional.Collections\bin\Release-Net452\Optional.xml" "Extras\Nuget_Collections\lib\net452\" /Y
XCOPY "Optional.Collections\bin\Release-Net46\Optional.dll" "Extras\Nuget_Collections\lib\net46\" /Y
XCOPY "Optional.Collections\bin\Release-Net46\Optional.xml" "Extras\Nuget_Collections\lib\net46\" /Y
XCOPY "Optional.Collections\bin\Release-Net461\Optional.dll" "Extras\Nuget_Collections\lib\net461\" /Y
XCOPY "Optional.Collections\bin\Release-Net461\Optional.xml" "Extras\Nuget_Collections\lib\net461\" /Y
XCOPY "Optional.Collections\bin\Release-Net462\Optional.dll" "Extras\Nuget_Collections\lib\net462\" /Y
XCOPY "Optional.Collections\bin\Release-Net462\Optional.xml" "Extras\Nuget_Collections\lib\net462\" /Y
XCOPY "Portable.Optional.Collections\bin\Release\Optional.dll" "Extras\Nuget_Collections\lib\netstandard1.0\" /Y
XCOPY "Portable.Optional.Collections\bin\Release\Optional.xml" "Extras\Nuget_Collections\lib\netstandard1.0\" /Y

XCOPY "Optional.Utilities\bin\Release-Net35\Optional.dll" "Extras\Nuget_Utilities\lib\net35\" /Y
XCOPY "Optional.Utilities\bin\Release-Net35\Optional.xml" "Extras\Nuget_Utilities\lib\net35\" /Y
XCOPY "Optional.Utilities\bin\Release-Net40\Optional.dll" "Extras\Nuget_Utilities\lib\net40\" /Y
XCOPY "Optional.Utilities\bin\Release-Net40\Optional.xml" "Extras\Nuget_Utilities\lib\net40\" /Y
XCOPY "Optional.Utilities\bin\Release-Net45\Optional.dll" "Extras\Nuget_Utilities\lib\net45\" /Y
XCOPY "Optional.Utilities\bin\Release-Net45\Optional.xml" "Extras\Nuget_Utilities\lib\net45\" /Y
XCOPY "Optional.Utilities\bin\Release-Net451\Optional.dll" "Extras\Nuget_Utilities\lib\net451\" /Y
XCOPY "Optional.Utilities\bin\Release-Net451\Optional.xml" "Extras\Nuget_Utilities\lib\net451\" /Y
XCOPY "Optional.Utilities\bin\Release-Net452\Optional.dll" "Extras\Nuget_Utilities\lib\net452\" /Y
XCOPY "Optional.Utilities\bin\Release-Net452\Optional.xml" "Extras\Nuget_Utilities\lib\net452\" /Y
XCOPY "Optional.Utilities\bin\Release-Net46\Optional.dll" "Extras\Nuget_Utilities\lib\net46\" /Y
XCOPY "Optional.Utilities\bin\Release-Net46\Optional.xml" "Extras\Nuget_Utilities\lib\net46\" /Y
XCOPY "Optional.Utilities\bin\Release-Net461\Optional.dll" "Extras\Nuget_Utilities\lib\net461\" /Y
XCOPY "Optional.Utilities\bin\Release-Net461\Optional.xml" "Extras\Nuget_Utilities\lib\net461\" /Y
XCOPY "Optional.Utilities\bin\Release-Net462\Optional.dll" "Extras\Nuget_Utilities\lib\net462\" /Y
XCOPY "Optional.Utilities\bin\Release-Net462\Optional.xml" "Extras\Nuget_Utilities\lib\net462\" /Y
XCOPY "Portable.Optional.Utilities\bin\Release\Optional.dll" "Extras\Nuget_Utilities\lib\netstandard1.0\" /Y
XCOPY "Portable.Optional.Utilities\bin\Release\Optional.xml" "Extras\Nuget_Utilities\lib\netstandard1.0\" /Y
